<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
    * Pagination query.
    *
    * @return object QueryBuilder
    */
   public function paginate()
   {
     return $this->_em->createQueryBuilder()
        ->select('t')
        ->from('AppBundle:Tag', 't');
   }
}
