<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Tag;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
    * Pagination query.
    *
    * @return object QueryBuilder
    */
   public function paginate()
   {
     return $this->_em->createQueryBuilder()
        ->select('t')
        ->from('AppBundle:Tag', 't');
   }

   /**
     * Save entity.
     *
     * @param Tag $tag Tag entity
     */
    public function save(Tag $tag)
    {
        $this->_em->persist($tag);
        $this->_em->flush();
    }

    /**
     * Delete entity.
     *
     * @param Tag $tag Tag entity
     */
    public function delete(Tag $tag)
    {
        $this->_em->remove($tag);
        $this->_em->flush();
    }
}
